# Generated by Django 5.0.2 on 2024-02-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finnest_app', '0004_commonfields_modulelist_modulepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulelist',
            name='commonId',
        ),
        migrations.RemoveField(
            model_name='modulepermission',
            name='commonId',
        ),
        migrations.RemoveField(
            model_name='modulepermission',
            name='moduleid',
        ),
        migrations.RemoveField(
            model_name='modulepermission',
            name='userid',
        ),
        migrations.DeleteModel(
            name='CommonFields',
        ),
        migrations.DeleteModel(
            name='ModuleList',
        ),
        migrations.DeleteModel(
            name='ModulePermission',
        ),
    ]
