# Generated by Django 5.0.2 on 2024-02-23 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finnest_app', '0005_remove_modulelist_commonid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=50, null=True)),
                ('createdDate', models.DateField()),
                ('lastMoodifiedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('lastMoodifiedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canAccess', models.BooleanField(default=False)),
                ('canCreate', models.BooleanField(default=False)),
                ('canEdit', models.BooleanField(default=False)),
                ('canDelete', models.BooleanField(default=False)),
                ('createdBy', models.CharField(blank=True, max_length=50, null=True)),
                ('createdDate', models.DateField()),
                ('lastMoodifiedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('lastMoodifiedDate', models.DateField()),
                ('moduleid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finnest_app.modulelist')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
