# Generated by Django 5.0.2 on 2024-02-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finnest_app', '0006_modulelist_modulepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulelist',
            name='createdDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulelist',
            name='lastMoodifiedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulepermission',
            name='createdDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulepermission',
            name='lastMoodifiedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
